### ISSUE TITLE
No translation file found for domain: 'weresync'

### ISSUE THREAD

**Issue by guygma** [DonyorM/weresync#9]
Hi there -- this looks like a great project. I haven't been able to get it running on Ubuntu 16.04 MATE amd64 or armhf. After installing either from pip or from the github I get the following output:

```
guygma@baggins:~/repos/github.com/clones/weresync$ weresync -h
Traceback (most recent call last):
  File "/usr/local/bin/weresync", line 9, in <module>
    load_entry_point('WereSync==1.0.4', 'console_scripts', 'weresync')()
  File "/usr/local/lib/python3.5/dist-packages/WereSync-1.0.4-py3.5.egg/weresync/interface.py", line 352, in main
    enable_localization()
  File "/usr/local/lib/python3.5/dist-packages/WereSync-1.0.4-py3.5.egg/weresync/interface.py", line 45, in enable_localization
    languages=LANGUAGES)
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'weresync'
```

Is this a known issue? I am using Python 3.5

**Comment by DonyorM** [comment]
Well, I thought I had fixed that. I'll look into why it's doing it again.

**Comment by DonyorM** [comment]
This should be fixed now. Please upgrade to version 1.0.6 and let me know if it works.

**Comment by guygma** [comment]
I've tried it on a few different systems, Ubuntu amd64/armhf and MacOS, and it still fails with the same error.

**Comment by DonyorM** [comment]
Right, figured out the issue. `sys.prefix` is different during installation than it is when you run by default on ubuntu. For now, running it in a virtualenv will probably work. I'll work on getting a fix.

**Comment by guygma** [comment]
Yup, it works in a virtualenv

**Comment by DonyorM** [comment]
Great, I definitely found the right issue then. I'll fix it as soon as I can.

**Comment by DonyorM** [comment]
Just uploaded WereSync 1.0.7 which should fix this issue.

**Comment by DonyorM** [comment]
@guygma I'm closing this for now, feel free to re-open if this didn't fix the issue.
